FROM centos:7

# 设置环境变量
ENV TERM=xterm

# 更新包管理器并安装
RUN yum update && \
    yum install gcc make -y && \
    yum clean all && \
    rm -rf /var/cache/yum

# 设置镜像的默认工作目录
WORKDIR /root

# 显示镜像构建完成后的基础信息
CMD ["bash"]